service: auth-server

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    CLIENT_ID: ${file(config.json):CLIENT_ID}
    CLIENT_SECRET: ${file(config.json):CLIENT_SECRET}
    PROJECT_ID: ${file(config.json):PROJECT_ID}
    CALENDAR_ID: ${file(config.json):CALENDAR_ID}
functions:
  getAuthURL:
    handler: handler.getAuthURL
    events:
      - http:
          path: api/get-auth-url
          method: get
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
